config/routes.rb
Ecatalog::Application.routes.draw do
  get "users/index"
  get "home" => "static_pages#home"
  get "users/show"

  #resources :sessions, :only => [:create]
  get "log_out" => "accounts/sessions#destroy", :as => "log_out"
  get "log_in" => "accounts/sessions#new", :as => "log_in"
  get "sign_up" => "accounts/users#new", :as => "sign_up"

  get "index" => "accounts/articles#index", :as => "accounts_index"
  get "locations" => "accounts/locations#index", :as => "locations_index"
    get "accounts/profile" => "accounts/users#edit" , :as=>"accounts_profile"
  get "contents"=>"taxons#index", :as =>"contents"

  get "companies" => "users#index", :as => "companies"
  root :to => "static_pages#home"

  match '/contents/*id', :to => 'taxons#show', :as => :nested_taxons

  resources :taxons
  resources :users , :path => "/companies"
  resources :promotions  do
    resources :tickets   do
      member  do
        get :register
        post :register
      end

    end
  end


namespace :accounts do
  resources :passwords
  resources :users do
    member do
      get :activate_account
    end

  end

  resources :sessions
  resources :locations
  resources :articles do
    resources :images do
    end
    resources :taxons do
      member do
        get :select
        delete :remove
      end
      collection do
        post :available
        get :selected
      end
    end
  end
  resources :promotions   do
    resources :ticket_batches do
      member do
        get :download
      end
    end
    resources :extractions do
      collection do
        post :extract
      end
    end
  end


  resources :taxonomies do
    member do
      get :get_children
    end
    resources :taxons
  end
end

#resources :images

  resources :articles
# resources :images

# resources :articles do
# resources :images do
# end
# resources :taxons do
# member do
# get :select
# delete :remove
# end
# collection do
# post :available
# get  :selected
# end
# end
# end
#
# resources :taxonomies do
# member do
# get :get_children
# end
# resources :taxons
# end

end

app/controllers/accounts/articles_controller.rb
class Accounts::ArticlesController < Accounts::BaseController
  before_filter :check_articles_limits, :only => [:new, :create]
  # GET /articles
  # GET /articles.xml
  def index
    @articles = current_user.articles.search(params[:search]).paginate(  :per_page => 12, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @articles }
    end
  end

  # GET /articles
  # GET /articles.xml
  def my_articles
    @articles = current_user.articles.all

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.xml
  def show
    @article = current_user.articles.find_by_permalink!(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.xml
  def new
    @article = Article.new


    respond_to do |format|
    	
     format.html {render :action => :new, :layout => !request.xhr?}
   #  format.html # new.html.erb
    format.json  { render :json => @article }
    end
  end

  # GET /articles/1/edit
  def edit
  	@article = current_user.articles.find_by_permalink!(params[:id])
  end

  # POST /articles
  # POST /articles.xml
  def create
    @article = current_user.articles.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to edit_accounts_article_path(@article, :notice => 'Article was successfully created.') }
    #    format.json  { render :json => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.json  { render :json => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.xml
  def update
   @article = current_user.articles.find_by_permalink!(params[:id])
   params[:article][:location_ids] ||= []

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(accounts_article_path(@article), :notice => 'Article was successfully updated.') }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.json  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.xml
  def destroy
 	@article = current_user.articles.find_by_permalink!(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(articles_url) }
      format.json  { head :ok }
    end
  end

  private
  def check_articles_limits
    unless current_user.special?
      if current_user.articles.size > 2
        flash[:alert] = t(:reached_max_articles)
        redirect_to accounts_articles_path
      end
    end
  end
end

app/controllers/accounts/base_controller.rb
class Accounts::BaseController < ApplicationController
	# before_filter :_reload_libs, :if => :_reload_libs?
	
	helper_method :current_user
  layout 'account'
	
 private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
# def _reload_libs
#   RELOAD_LIBS.each do |lib|
#     require_dependency lib
#   end
# end
#  
# def _reload_libs?
#   defined? RELOAD_LIBS
# end

end

app/controllers/accounts/extractions_controller.rb
class Accounts::ExtractionsController < Accounts::BaseController
  def extract
    promotion = current_user.promotions.find_by_permalink!(params[:promotion_id])
    if promotion.extractions.count < promotion.extractions_count and promotion.ended?

      ticket = promotion.tickets.not_extracted.offset(rand(promotion.tickets.not_extracted.count)).first
      extraction = Extraction.new(:promotion => promotion, :ticket => ticket)
      #@extraction.ticket.( @ticket)
      #@extraction.promotion  = @promotion
      extraction.save
      #send winning mail
      TicketMailer.winner_notification(extraction.ticket,promotion).deliver
      respond_to do |format|
        flash[:success] = 'Extragere efectuata cu success.'
        format.html { redirect_to accounts_promotion_path(promotion) }
      end
    else
      respond_to do |format|
        flash[:alert] = 'Nu pot fi efectuate extrageri.'
        format.html { redirect_to accounts_promotion_path(promotion) }
      end
    end

  end
end

app/controllers/accounts/images_controller.rb
class Accounts::ImagesController < Accounts::BaseController
  before_filter :check_article_images_limits, :only => [:new, :create]
#	before_filter :load_data

 def index
 	  @article = current_user.articles.find_by_permalink(params[:article_id])
 	  respond_to do |format|
 	        format.html # index.html.erb
 	        # format.json  { render :json => @article }
 	      end
 end	

def new
  @image = Image.new
  @article = current_user.articles.find_by_permalink(params[:article_id])
  respond_to do |format|
      
     format.html {render :action => :new, :layout => !request.xhr?}
     format.html # new.html.erb
     #format.json  { render :json => @article }
    end
end

def create
  image_data = params[:image]
  @article = current_user.articles.find_by_permalink(params[:article_id])
  @image = @article.images.build(image_data)
  
   respond_to do |format|
      if @image.save
        flash[:success] = "Photo successfully uploaded"
        format.html { redirect_to accounts_article_images_url(@article) }
      else
        format.html { render :action => "new" }
      end
    end
end

 def edit
   @article = current_user.articles.find_by_permalink(params[:article_id])
   @image = Image.find(params[:id])

 end

 def destroy

     @article = current_user.articles.find_by_permalink!(params[:article_id])
     @image = Image.find(params[:id])
     @image.destroy
     flash[:success] = "Photo successfully deleted"
     respond_to do |format|
       format.html { redirect_to  accounts_article_images_url(@article) }
       format.js
      end
end


def update
  @article = current_user.articles.find_by_permalink!(params[:article_id])
  @image = Image.find(params[:id])
   image_data =  params[:image]

  respond_to do |format|
    if @image.update_attributes(image_data)
      puts "updated"

      format.html { redirect_to(accounts_article_images_url(@article), :notice => 'Imaginea a fost actualizata cu success!') }
      format.json  { head :ok }
    else
      puts "else"

      format.html { render :action => "edit" }
      format.json  { render :xml => @image.errors, :status => :unprocessable_entity }
    end
  end
end

  

  private

  def load_data
    @article = Article.find_by_permalink(params[:article_id])
  end

  def set_viewable

      object.viewable = @article
  end

  def destroy_before
    @viewable = object.viewable
  end

  def check_article_images_limits
    unless current_user.special?
      @article = current_user.articles.find_by_permalink!(params[:article_id])
      if @article.images.size > 2
        flash[:alert] = t(:reached_max_images)
        redirect_to accounts_article_images_path(@article)
      end
    end
  end

end

app/controllers/accounts/locations_controller.rb
class Accounts::LocationsController < Accounts::BaseController
  before_filter :check_locations_limits, :only => [:new, :create]

  def index
    @locations = current_user.locations

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @locations }
    end
  end



  def show
      @location = current_user.locations.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json  { render :json => @location }
      end
    end

    # GET /locations/new
    # GET /locations/new.xml
    def new
      @location = Location.new
      respond_to do |format|

       format.html {render :action => :new, :layout => !request.xhr?}
     #  format.html # new.html.erb
      format.json  { render :json => @location }
      end

    end

    # GET /locations/1/edit
    def edit
    	@location = current_user.locations.find(params[:id])
    end

    # POST /locations
    # POST /locations.xml
    def create
      @location = current_user.locations.new(params[:location])

      respond_to do |format|
        if @location.save
          format.html { redirect_to accounts_locations_path( :notice => 'location was successfully created.') }
      #    format.json  { render :json => @location, :status => :created, :location => @location }
        else
          format.html { render :action => "new" }
          format.json  { render :json => @location.errors, :status => :unprocessable_entity }
        end
      end
    end

    # PUT /locations/1
    # PUT /locations/1.xml
    def update
     @location = current_user.locations.find(params[:id])

      respond_to do |format|
        if @location.update_attributes(params[:location])
          format.html { redirect_to(accounts_location_path(@location), :notice => 'location was successfully updated.') }
          format.json  { head :ok }
        else
          format.html { render :action => "edit" }
          format.json  { render :xml => @location.errors, :status => :unprocessable_entity }
        end
      end
    end

    # DELETE /locations/1
    # DELETE /locations/1.xml
    def destroy
   	@location = current_user.locations.find(params[:id])
      @location.destroy

      respond_to do |format|
        format.html { redirect_to(accounts_locations_url) }
        format.json  { head :ok }
      end
    end

  private
  def  check_locations_limits
   unless current_user.special?
       if current_user.locations.size > 2
         flash[:alert] = t(:reached_max_locations)
         redirect_to accounts_locations_path
       end
   end
  end

end

app/controllers/accounts/passwords_controller.rb
class Accounts::PasswordsController < Accounts::BaseController
  def new
  end
  def create
    user = User.find_by_email(params[:email])

    if user
      user.send_password_reset
      redirect_to log_in_url, :notice=> t(:password_reset_sent)
    else
      redirect_to log_in_url,:alert => "Nu exista un utilizator inregistrat cu acest email!"
    end

  end
  def edit
    @user = User.find_by_login_token!(params[:id])
  end
  def update
    @user = User.find_by_login_token!(params[:id])
    if @user.login_token_generated_at  < 2.hours.ago
      redirect_to new_accounts_password_path, :alert => "Linkul a expirat."
    elsif @user.update_attributes(params[:user])
      redirect_to log_in_url, :notice => t(:password_reset_success)
    else
      render :edit
    end
  end
end

app/controllers/accounts/promotions_controller.rb
class Accounts::PromotionsController <  Accounts::BaseController
  before_filter :check_promotions_limits, :only => [:new, :create]

  def index
    @promotions = current_user.promotions

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @promotions }
    end
  end


  def show
    @promotion = current_user.promotions.find_by_permalink!(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @promotion }
    end
  end

  # GET /promotions/new
  # GET /promotions/new.xml
  def new
    @promotion = Promotion.new
    respond_to do |format|

      format.html {render :action => :new, :layout => !request.xhr?}
      #  format.html # new.html.erb
      format.json  { render :json => @promotion}
    end

  end

  # GET /promotions/1/edit
  def edit
    @promotion = current_user.promotions.find_by_permalink!(params[:id])
    if @promotion.started?
      respond_to do |format|
        format.html { redirect_to(accounts_promotions_url) }
        format.json  { head :ok }
      end
      return
    end
  end

  # POST /promotions
  # POST /promotions.xml
  def create
    @promotion = current_user.promotions.new(params[:promotion])

    respond_to do |format|
      if @promotion.save
        format.html { redirect_to accounts_promotions_path( :notice => t(:promotion_created_successfully)) }
        #    format.json  { render :json => @location, :status => :created, :location => @location }
      else
        format.html { render :action => "new" }
        format.json  { render :json => @promotion.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /promotions/1
  # PUT /promotions/1.xml
  def update
    @promotion = current_user.promotions.find_by_permalink!(params[:id])
    if @promotion.started?
      respond_to do |format|
        format.html { redirect_to(accounts_promotions_url) }
        format.json  { head :ok }
      end
      return
    end
    respond_to do |format|
      if @promotion.update_attributes(params[:promotion])
        format.html { redirect_to(accounts_promotion_path(@promotion), :notice => 'promotion was successfully updated.') }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.json  { render :xml => @promotion.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /promotions/1
  # DELETE /promotions/1.xml
  def destroy
    @promotion = current_user.promotions.find_by_permalink!(params[:id])
    if @promotion.started?
      respond_to do |format|
        format.html { redirect_to(accounts_promotions_url) }
        format.json  { head :ok }
      end
      return
    end
    @promotion.destroy

    respond_to do |format|
      format.html { redirect_to(accounts_promotions_url) }
      format.json  { head :ok }
    end
  end

  private
  def check_promotions_limits
    unless current_user.special?
      if current_user.promotions.size > 1
        flash[:alert] = t(:reached_max_promotions)
        redirect_to accounts_promotions_path
      end
    end
  end


end

app/controllers/accounts/sessions_controller.rb
class Accounts::SessionsController < Accounts::BaseController
def new
end

def create
  user = User.authenticate(params[:email], params[:password])
  if user
    if  user.activated?
      session[:user_id] = user.id
      redirect_to accounts_index_path, :notice => "Logged in!"
      else
        flash.now.alert = "Contul dvs nu a fost activat. Verificati posta electronica!"
      render "new"
    end

  else
    flash.now.alert = "Invalid email or password"
    render "new"
  end
end

def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Logged out!"
end
end

app/controllers/taxons_controller.rb
class TaxonsController < ApplicationController

 def index
   @taxons = Taxon.root.children
   @articles = Article.new_arrivals.paginate(:per_page=>12, :page=>params[:page])
 end

   def show
    @taxon = Taxon.find_by_permalink(params[:id])

    return unless @taxon

    @searcher = Ecatalog::Config.searcher_class.new(params.merge(:taxon => @taxon.id  ))
    @articles = @searcher.retrieve_articles
    puts @articles.count.to_s + "####################Controlles"
    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @taxon }
    end
   end

 private
       def accurate_title
         @taxon ? @taxon.name : super
       end
end

app/helpers/accounts/extractions_helper.rb
module Accounts::ExtractionsHelper
end

app/helpers/accounts/locations_helper.rb
module Accounts::LocationsHelper
end

app/helpers/accounts/passwords_helper.rb
module Accounts::PasswordsHelper
end

app/helpers/accounts/promotions_helper.rb
module Accounts::PromotionsHelper
end

app/helpers/accounts/ticket_batches_helper.rb
module Accounts::TicketBatchesHelper
end

app/helpers/taxon_helper.rb
module TaxonHelper
end

app/views/accounts/taxons/_form.html.erb
<%= hook :admin_inside_taxon_form, {:f => f} do %>
  <%= f.field_container :name do %>
    <%= f.label :name, t("name") %> <span class="required">*</span><br />
    <%= error_message_on :taxon, :name, :class => 'fullwidth title'  %>
    <%= text_field :taxon, :name  %>
  <% end %>

  <%= f.field_container :permalink_part do %>
    <%= f.label :permalink_part, t("permalink") %><span class="required">*</span><br />
    <%= @taxon.permalink.split("/")[0...-1].join("/") + "/" %><%= text_field_tag :permalink_part, @permalink_part  %>
  <% end %>

  <%= f.field_container :icon do %>
    <%= f.label :icon, t('icon') %><br />
    <%= f.file_field :icon %>
  <% end %>

  <%= f.field_container :description do %>
    <%= f.label :description, t(:description) %><br />
    <%= f.text_area :description %>
  <% end %>

<% end %>

app/views/accounts/taxons/_taxon_table.html.erb
<table class="index">
  <thead>
  	<tr>
  		<th><%= t("name") %></th>
  		<th><%= 'Calea' %></th>
  		<th><%= t(:action) %></th>
  	</tr>
  </thead>
  <tbody>
    <% @taxons.each do |taxon| %>
      <tr id="<%= dom_id(taxon)%>">
        <td><%= taxon.name %></td>
        <td><%= taxon.permalink%></td>
  	    <td class="actions">	                         
		      <%= link_to "Remove",  remove_accounts_article_taxon_path(@article, taxon.id), :method=>:delete %>
  	    </td>        
      </tr>
    <% end %>
    <% if @taxons.empty? %>
     <tr><td colspan="3"><%= 'none' %>.</td></tr>
    <% end %>
  </tbody>
</table>

app/views/accounts/taxons/available.js.erb
<script type="text/javascript">
  function displayRow(){
    var row = document.getElementById("captionRow");
    if (row.style.display == '') row.style.display = 'none';
    else row.style.display = '';
  }
</script>
<h4><%= "Categorii disponibile" %></h4>
<table class="index">
  <thead>
    <tr>
      <th><%= t("name") %></th>
      <th><%= t("path") %></th>
      <th><%= t("action") %></th>
    </tr>
  </thead>
  <tbody>
    <% @available_taxons.each do |taxon| %>
      <tr id="<%= dom_id(taxon, :sel) %>">
        <td><%= taxon.name %></td>
        <td><%=  taxon.permalink %></td>
        <td class="actions">
          <%= link_to  t("select"),
          #:controller=>"accounts/taxons",:article_id=>@article.permalink,:id=>taxon.id,:action => :select ,
                            select_accounts_article_taxon_path(@article, taxon.id),
                           :remote => true, :class => 'iconlink' %>
        </td>
      </tr>
    <% end %>
    <% if @available_taxons.empty? %>
     <tr><td colspan="3"><%= t('no_match_found') %>.</td></tr>
    <% end %>
  </tbody>
</table>

app/views/accounts/taxons/edit.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<h1><%= t("taxon_edit")%></h1>

<%= form_for(:taxon, :url => admin_taxonomy_taxon_url, :html => { :method => :put, :multipart => true}) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>

  <p class="form-buttons">
    <%= button t("update") %> <%= t("or") %> <%= link_to t("cancel"), edit_admin_taxonomy_url(@taxonomy) %>
  </p>
<% end %>

app/views/accounts/taxons/remove.html.erb
<%= render :partial => "taxon_table", :locals => {:taxons => @taxons} %>

app/views/accounts/taxons/select.js.erb
$("#selected-taxons").html("<%= escape_javascript(render(:partial => "taxon_table", :locals => {:taxons => @taxons})) %>");
$("#<%= dom_id @taxon, :sel %>").hide();

app/views/accounts/taxons/selected.html.erb
<%= #render :partial => 'shared/article_sub_menu'
 %>

<%= render :partial => 'shared/article_tabs', :locals => {:current => "Taxons"} %>
<div id="selected-taxons">
  <%= render :partial => "taxon_table", :locals => {:taxons => @taxons} %>
</div>


<%= form_tag('#') do %>
  <label><%= 'Caută' %>:</label>
  <input id="searchtext" size="25">
<% end %>

<%= javascript_tag do %>
    function search_for_taxons(){
    $.ajax({
    data: {q: $("#searchtext").val() },
    dataType: 'html',
    success: function(request){
    jQuery('#search_hits').html(request);
    },
    type: 'POST',
    url: '<%= available_accounts_article_taxons_url(@aricle, :format => 'js') %>'
    });
    }

    $("#searchtext").keypress(function (e) {
    if ((e.which && e.which == 13) || (e.keyCode && e.keyCode == 13)) {
    search_for_taxons();

    return false;
    } else {
    return true;
    }
    });

    $("#searchtext").delayedObserver(function() {
    search_for_taxons();
    }, 0.75);
<% end %>

<br/>
<div id="search_hits"></div>