config/routes.rb
Ecatalog::Application.routes.draw do
  get "users/index"
  get "home" => "static_pages#home"
  get "users/show"

  #resources :sessions, :only => [:create]
  get "log_out" => "accounts/sessions#destroy", :as => "log_out"
  get "log_in" => "accounts/sessions#new", :as => "log_in"
  get "sign_up" => "accounts/users#new", :as => "sign_up"

  get "index" => "accounts/articles#index", :as => "accounts_index"
  get "locations" => "accounts/locations#index", :as => "locations_index"
    get "accounts/profile" => "accounts/users#edit" , :as=>"accounts_profile"
  get "contents"=>"taxons#index", :as =>"contents"

  get "companies" => "users#index", :as => "companies"
  root :to => "static_pages#home"

  match '/contents/*id', :to => 'taxons#show', :as => :nested_taxons

  resources :taxons
  resources :users , :path => "/companies"
  resources :promotions  do
    resources :tickets   do
      member  do
        get :register
        post :register
      end

    end
  end


namespace :accounts do
  resources :passwords
  resources :users do
    member do
      get :activate_account
    end

  end

  resources :sessions
  resources :locations
  resources :articles do
    resources :images do
    end
    resources :taxons do
      member do
        get :select
        delete :remove
      end
      collection do
        post :available
        get :selected
      end
    end
  end
  resources :promotions   do
    resources :ticket_batches do
      member do
        get :download
      end
    end
    resources :extractions do
      collection do
        post :extract
      end
    end
  end


  resources :taxonomies do
    member do
      get :get_children
    end
    resources :taxons
  end
end

#resources :images

  resources :articles
# resources :images

# resources :articles do
# resources :images do
# end
# resources :taxons do
# member do
# get :select
# delete :remove
# end
# collection do
# post :available
# get  :selected
# end
# end
# end
#
# resources :taxonomies do
# member do
# get :get_children
# end
# resources :taxons
# end

end

app/models/article.rb
class Article < ActiveRecord::Base

	validates :name, :presence => true
	validates :price, :presence => true
	
	belongs_to :user
	  
	has_many :images, :as => :viewable, :order => :position, :dependent => :destroy
	has_and_belongs_to_many :taxons
  has_and_belongs_to_many :article_groups
  has_and_belongs_to_many :locations

    include ::Scopes::Article
   #SCOPES
  scope :not_deleted,     where("articles.deleted_at is NULL")

  scope :available,       lambda { |*on| where("articles.available_on <= ? OR 1=1 ", on.first || Time.zone.now ) }
  scope :active,          lambda{ not_deleted.available }
  scope :new_arrivals,    lambda { |*on| where("articles.created_at > ?", on.first || 1.weeks.ago ) }
	
	  def featured_image(image_size = :small)
      images.first ? images.first.attachment.url(image_size) : "no_image_#{image_size.to_s}.jpg"
    end
  
  make_permalink

  # @param [Object] search
  def self.search(search)
     if search
           where('name LIKE ?', "%#{search}%")
         else
          scoped
     end
   end

  def to_param
    permalink.present? ? permalink : (permalink_was || name.to_s.to_url)
  end


end

app/controllers/accounts/articles_controller.rb
class Accounts::ArticlesController < Accounts::BaseController
  before_filter :check_articles_limits, :only => [:new, :create]
  # GET /articles
  # GET /articles.xml
  def index
    @articles = current_user.articles.search(params[:search]).paginate(  :per_page => 12, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @articles }
    end
  end

  # GET /articles
  # GET /articles.xml
  def my_articles
    @articles = current_user.articles.all

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.xml
  def show
    @article = current_user.articles.find_by_permalink!(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.xml
  def new
    @article = Article.new


    respond_to do |format|
    	
     format.html {render :action => :new, :layout => !request.xhr?}
   #  format.html # new.html.erb
    format.json  { render :json => @article }
    end
  end

  # GET /articles/1/edit
  def edit
  	@article = current_user.articles.find_by_permalink!(params[:id])
  end

  # POST /articles
  # POST /articles.xml
  def create
    @article = current_user.articles.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to edit_accounts_article_path(@article, :notice => 'Article was successfully created.') }
    #    format.json  { render :json => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.json  { render :json => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.xml
  def update
   @article = current_user.articles.find_by_permalink!(params[:id])
   params[:article][:location_ids] ||= []

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(accounts_article_path(@article), :notice => 'Article was successfully updated.') }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.json  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.xml
  def destroy
 	@article = current_user.articles.find_by_permalink!(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(articles_url) }
      format.json  { head :ok }
    end
  end

  private
  def check_articles_limits
    unless current_user.special?
      if current_user.articles.size > 2
        flash[:alert] = t(:reached_max_articles)
        redirect_to accounts_articles_path
      end
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.xml
  def index
    @articles = Article.search(params[:search]).paginate(  :per_page => 12, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @articles }
    end

  end

  
  # GET /articles/1
  # GET /articles/1.xml
  def show
    @article = Article.find_by_permalink (params[:id])
    @locations =  @article.locations
    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @article }
    end
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_cart_form.html.erb
  <div data-hook="inside_product_cart_form" itemprop="offers" itemscope itemtype="http://schema.org/Offer">


    <% if @article.price %>
      <div data-hook="product_price" class="columns five  omega ">
        
        <div id="product-price">
          <h6 class="product-section-title"><%= t(:price) %></h6>
          <div><span class="price selling" itemprop="price"><%= number_to_currency(@article.price , :unit => "MDL", :separator => ",", :delimiter => "",  :format => "%n %u" ) %></span></div>
        </div>


      </div>
    <% end %>    

  </div>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
    <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/_image.html.erb
<% if image %> 
  <%= image_tag image.attachment.url(:article), :itemprop => "description" %>
<% else %>
  <%=
  article_image(@article, :itemprop => "image")
  #image_tag @article.images.first.attachment.url(:original), :itemprop => "image"
  %>
<% end %>

app/views/articles/_thumbnails.html.erb
<!-- no need for thumnails unless there is more then one image -->
<% if article.images.size > 1 %>
  <ul id="article-thumbnails" class="thumbnails inline" data-hook>
    <% article.images.each do |i| %>
      <li class="tmb-all" id="tmb-<%= i.id.to_s %>"><%= link_to image_tag(i.attachment.url(:mini)), i.attachment.url(:article) %></li>
    <% end %>

  </ul>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>


<%= render :partial => 'shared/article_tabs', :locals => {:current => "Article Details"} %>
<br class="clear" />

<%= form_for(@article, :url => article_url, :html => { :method => :put, :multipart => true }) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  
  <%= link_to 'Show', @article %> |
  <%= link_to 'Back', articles_path %>

<% end %>

app/views/articles/index.html.erb
<% content_for :sidebar do %>
      <%= #render "shared/taxonomies" 
      %>
<% end %>

<%=render :partial => "shared/articles", :locals => {:articles => @articles} %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>
<!--
<p>
  <b>Name:</b>
  <%= @article.name %>
</p>

<p>
  <b>Description:</b>
  <%= @article.description %>
</p>

<p>
  <b>Created at:</b>
  <%= @article.created_at %>
</p>




<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>-->


<div data-hook="article_show" itemscope itemtype="http://schema.org/Product">
  <% @body_id = 'article-details' %>

  <div class="columns six alpha" data-hook="product_left_part">
    <div class="row" data-hook="product_left_part_wrap">

      <div id="article-images" data-hook="article-images">
        <div id="main-image" data-hook>
          <%= render :partial => 'image' %>
        </div>
        <div id="thumbnails" data-hook>
          <%= render :partial => 'thumbnails', :locals => {:article => @article} %>
        </div>
      </div>

    </div>
  </div>

  <div class="columns ten omega" data-hook="product_right_part">
    <div class="row" data-hook="product_right_part_wrap">

      <div id="article-description" data-hook="product_description">

        <h1 class="article-title" itemprop="name"><%= @article.name %></h1>

        <div itemprop="description" data-hook="product_description">
          <%= (@article.description) rescue t(:product_has_no_description) %>
        </div>
      </div>
      <div id="cart-form" data-hook="cart_form">
        <%= render :partial => 'cart_form' %>
        <p>
          <b>Oferit de:</b>
          <%= link_to @article.user.name, user_path(@article.user) %>

        </p>
        <% if @article.locations  %>
            <%= render :partial => 'shared/locations', :locals => {:locations=> @article.locations  }%>
        <% end %>
      </div>
    </div>
  </div>

</div>