config/routes.rb
Ecatalog::Application.routes.draw do
  get "users/index"
  get "home" => "static_pages#home"
  get "users/show"

  #resources :sessions, :only => [:create]
  get "log_out" => "accounts/sessions#destroy", :as => "log_out"
  get "log_in" => "accounts/sessions#new", :as => "log_in"
  get "sign_up" => "accounts/users#new", :as => "sign_up"

  get "index" => "accounts/articles#index", :as => "accounts_index"
  get "locations" => "accounts/locations#index", :as => "locations_index"
    get "accounts/profile" => "accounts/users#edit" , :as=>"accounts_profile"
  get "contents"=>"taxons#index", :as =>"contents"

  get "companies" => "users#index", :as => "companies"
  root :to => "static_pages#home"

  match '/contents/*id', :to => 'taxons#show', :as => :nested_taxons

  resources :taxons
  resources :users , :path => "/companies"
  resources :promotions  do
    resources :tickets   do
      member  do
        get :register
        post :register
      end

    end
  end


namespace :accounts do
  resources :passwords
  resources :users do
    member do
      get :activate_account
    end

  end

  resources :sessions
  resources :locations
  resources :articles do
    resources :images do
    end
    resources :taxons do
      member do
        get :select
        delete :remove
      end
      collection do
        post :available
        get :selected
      end
    end
  end
  resources :promotions   do
    resources :ticket_batches do
      member do
        get :download
      end
    end
    resources :extractions do
      collection do
        post :extract
      end
    end
  end


  resources :taxonomies do
    member do
      get :get_children
    end
    resources :taxons
  end
end

#resources :images

  resources :articles
# resources :images

# resources :articles do
# resources :images do
# end
# resources :taxons do
# member do
# get :select
# delete :remove
# end
# collection do
# post :available
# get  :selected
# end
# end
# end
#
# resources :taxonomies do
# member do
# get :get_children
# end
# resources :taxons
# end

end

app/views/shared/_article_sub_menu.html.erb
<% content_for :sub_menu do %>
  <ul id="sub_nav">
    <%= hook :admin_article_sub_tabs do %>
      <%= tab :articles, :match_path => '/articles' %>
      <%= tab :option_types, :match_path => '/option_types' %>
      <%= tab :properties %>
      <%= tab :prototypes %>
      <%= tab :article_groups, :match_path => '/articles_groups', :css_class => 'last' %>
    <% end %>
  </ul>
<% end %>

app/views/shared/_article_tabs.html.erb
<h1></h1>

<% content_for :sidebar do %>

  <h3><%= @article.name  %></h3>
  <br class="clear" />

  <ul class="sidebar article-menu">
   

      <li<%== ' class="active"' if current == "Article Details" %>>
        <%= link_to t("product_details"), edit_accounts_article_path(@article) %>
      </li>
      <li<%== ' class="active"' if current == "Images" %>>
        <%= link_to t("images"), accounts_article_images_path(@article) %>
      </li>
      <li<%== ' class="active"' if current == "Taxons" %>>
        <%= link_to t("categories"), accounts_article_taxons_path(@article) %>
      </li>
  
  </ul>
  <br class="clear" />

<% end %>

app/views/shared/_articles.html.erb
<div data-hook="homepage_products">
<% if @articles.any? %>
<ul class="article-listing">
  <% @articles.each do |article| %>
   
      <li id="article_<%= article.id %>">
        <div class="article-image">
                  <%= link_to small_image(article, :itemprop => "name"), article %>
        </div>


          <%= #link_to image_tag(article.featured_image(:small),),article
#link_to small_image(product), product
            %>
          <%= link_to raw(article.name + " <span class='price selling'>#{ number_to_currency(article.price , :unit => "MDL", :separator => ",", :delimiter => "",  :format => "%n %u" )}</span>"),article,:class => 'info' %>
       
      </li>
<% end %>
  
</ul>
      <hr class="space">
<%= will_paginate( @articles, :previous_label => "&#171; #{t('previous')}", :next_label => "#{t('next')} &#187;")
%>
<% end %>

    </div>

app/views/shared/_locations.html.erb
<ul>
  <%@locations.each do  |location| %>
      <li> <a class="tooltip" href="#">
        <%= location.name %>
        <span class="custom information"><em>Contact Information</em><%= location.contact_information %></span>
      </a>
      </li>
  <% end %>
</ul>

app/views/shared/_search.html.erb
<%= form_tag articles_path, :method => :get do %>
    <%= text_field_tag :search, params[:search] , :class=>"search" %>
    <%= submit_tag "Caută", :name => nil, :class=>"submit"  %>
 <%end%>